name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.9.2
homepage: https://github.com/leisim/logger

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  test: any
  pedantic: ^1.9.0
