name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.8.3
homepage: https://github.com/leisim/logger

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  io: 0.3.3

dev_dependencies:
  test: any
  pedantic: ^1.9.0
