name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 1.0.0-nullsafety.0
homepage: https://github.com/leisim/logger

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.10
  pedantic: ^1.10.0-nullsafety.3
